name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: build
      uses: xdtianyu/actions-android-ci@v1.0.0
      env:
        keypass: ${{ secrets.keypass }}
        storepass: ${{ secrets.storepass }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        BUILD_SHA: ${{ github.sha }}
      with: 
        args: '"
        ./gradlew assembleCi assemblePlay;
        BUILD_SHA_SHORT=$(git rev-parse --short $(BUILD_SHA);
        cp app/build/outputs/apk/ci/*.apk TelegramXMods-ci-${BUILD_SHA_SHORT}.apk;
        cp app/build/outputs/apk/play/*.apk TelegramXMods-play-${BUILD_SHA_SHORT}.apk;
        ./scripts/deploy-telegram.sh
        "'
