name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: checkout submodule
      run: git submodule sync --recursive && git submodule update --init --recursive
      
    - name: build
      uses: xdtianyu/actions-android-ci@master
      env:
        keypass: ${{ secrets.keypass }}
        storepass: ${{ secrets.storepass }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        BUILD_SHA: ${{ github.sha }}
      with: 
        args: '"
        source /opt/setup-android-sdk.sh;
        ./gradlew assembleCi;
        find;
        BUILD_SHA_SHORT=$(git rev-parse --short ${BUILD_SHA});
        cp app/build/outputs/apk/ci/*.apk TelegramXMods-ci-${BUILD_SHA_SHORT}.apk;
        cp app/build/outputs/apk/play/*.apk TelegramXMods-play-${BUILD_SHA_SHORT}.apk;
        chmod +x scripts/deploy-telegram.sh
        ./scripts/deploy-telegram.sh
        "'
